DOC-742: Document changes to lists plugin with multiple text blocks selected
tinymce/tinymce-docs pull request #1823
Opened 2021-01-05 23:10 UTC by JamesToohey

Related Ticket: DOC-742

Description of Changes:

Minor enhancement note for changes to `lists` plugin behaviour on selections across multiple text blocks.

Pre-checks:
- [x] Branch prefixed with `feature/` or `hotfix/`
- [x] ~~`_data/nav.yml` has been updated (if applicable)~~
- [x] ~~Files has been included where required (if applicable)~~
- [x] ~~Files removed have been deleted, not just excluded from the build (if applicable)~~
- [x] ~~(New product features only) Release Note added~~

Review:
- [ ] Documentation Team Lead has reviewed
- [ ] Product Manager has reviewed

2021-01-06 06:10 UTC, metricjs approved these changes

2021-01-06 06:10 UTC, metricjs commented on release-notes/release-notes57.md
> +- The `lists` plugin will now apply list styles to all text blocks within a selection.
Might it be worth mentioning that it applies to mixed paragraph/list content? Really not sure

2021-01-06 06:39 UTC, lnewson requested changes
As discussed during the call today, we want to call this out so it should be more of a "blurb" than a changelog entry.

2021-01-06 08:07 UTC, EkimChau approved these changes

2021-01-06 08:08 UTC, EkimChau approved these changes

2021-01-08 00:26 UTC, metricjs approved these changes

2021-01-08 00:26 UTC, metricjs commented on release-notes/release-notes57.md
> +- Mixes of existing lists and text blocks.
```suggestion
- Combinations of existing lists and text blocks.
```
`Mixes` just reads weird to me. Not entirely sure this is better though... @tylerkelly13

2021-01-08 05:58 UTC, tylerkelly13 requested changes
please improve the description

2021-01-08 05:58 UTC, tylerkelly13 commented on release-notes/release-notes57.md
> +Improved behavior when using the `lists` plugin to add lists to selections containing:
```suggestion
The `lists` plugin has been updated to improve the handling of content containing:
```

2021-01-08 05:58 UTC, tylerkelly13 commented on release-notes/release-notes57.md
> +Improved behavior when using the `lists` plugin to add lists to selections containing:
Trying to make it more of a complete sentence? It reads really weird at the moment. feels too much like a changelog entry.

2021-01-08 06:31 UTC, ashfordneil approved these changes

2021-01-11 01:12 UTC, lnewson commented on release-notes/release-notes57.md
> +- Multiple text blocks.
text blocks? That sounds confusing to me, as text can't be block elements.

2021-01-11 01:12 UTC, lnewson commented on release-notes/release-notes57.md
> +The `lists` plugin has been updated to improve the handling of content containing:
Should this say something along the lines of "when converting content to lists"? As atm it's not very clear what "handling" is referring to here.

2021-01-12 23:24 UTC, lnewson approved these changes

2021-01-13 01:49 UTC, tylerkelly13 approved these changes

2021-01-13 01:55 UTC, merged