DOC-850: Document new plugin commands
tinymce/tinymce-docs pull request #2026
Opened 2021-07-12 04:56 UTC by diogo405

Related Ticket: 

Description of Changes:
* Added new commands - `mceEmoticons`, `mceTemplate`, and `mceWordCount` - to commands page 

Pre-checks:
- [x] Branch prefixed with `feature/` or `hotfix/`
- [x] ~`_data/nav.yml` has been updated (if applicable)~
- [x] Files has been included where required (if applicable)
_includes/commands/emoticons-cmds.md
_includes/commands/wordcount-cmds.md
- [x] ~Files removed have been deleted, not just excluded from the build (if applicable)~
- [x] (New product features only) Release Note added

Review:
- [ ] Documentation Team Lead has reviewed
- [ ] Product Manager has reviewed

2021-07-12 06:35 UTC, tylerkelly13 requested changes
Release note needs work, otherwise LGTM!

2021-07-12 06:35 UTC, tylerkelly13 commented on release-notes/release-notes59.md
> +- Added new plugin commands: `mceEmoticons` (emoticons), `mceWordCount` (wordcount), and `mceTemplate` (template)
Needs a bit more detail, like
```
- Added new open dialog commands for the following plugins:
  - Emoticons (`mceEmoticons`)
  - Word Count (`mceWordCount`)
  - Template (`mceTemplate`)
```

2021-07-12 07:58 UTC, lnewson commented on _includes/commands/emoticons-cmds.md
> +**Examples**
```suggestion
**Example**
```

2021-07-12 22:18 UTC, diogo405 commented on release-notes/release-notes59.md
> +- Added new plugin commands: `mceEmoticons` (emoticons), `mceWordCount` (wordcount), and `mceTemplate` (template)
Right, changed 👍

2021-07-12 22:20 UTC, diogo405 commented on _includes/commands/emoticons-cmds.md
> +**Examples**
Fixed.

2021-07-13 01:18 UTC, tylerkelly13 approved these changes

2021-07-13 02:14 UTC, lnewson approved these changes

2021-07-13 02:14 UTC, lnewson commented on release-notes/release-notes59.md
> +  - `mceTemplate` shows the Template selector dialog
```suggestion
- Added new plugin commands:
  - `mceEmoticons` opens the Emoticons dialog.
  - `mceWordCount` displays the Word Count summary dialog.
  - `mceTemplate` shows the Template dialog.
```

2021-07-13 02:14 UTC, lnewson commented on _includes/commands/wordcount-cmds.md
> +| mceWordCount      | Opens the Word Count dialog. |
```suggestion
| mceWordCount      | Opens the Word Count summary dialog. |
```
This is to keep it consistent with what we've said in the release notes.

2021-07-13 03:51 UTC, EkimChau approved these changes

2021-07-13 04:00 UTC, merged