TINY-7670: New language icon
tinymce/tinymce-docs pull request #2043
Opened 2021-08-02 06:03 UTC by ashfordneil

Related Ticket: 

Description of Changes:
* Placeholder text

Pre-checks:
- [ ] Branch prefixed with `feature/` or `hotfix/`
- [ ] `_data/nav.yml` has been updated (if applicable)
- [ ] Files has been included where required (if applicable)
- [ ] Files removed have been deleted, not just excluded from the build (if applicable)
- [ ] (New product features only) Release Note added

Review:
- [ ] Documentation Team Lead has reviewed
- [ ] Product Manager has reviewed

2021-08-02 06:09 UTC, diogo405 approved these changes

2021-08-02 06:41 UTC, tylerkelly13 approved these changes

2021-08-02 21:28 UTC, lnewson requested changes
Changes look good, but as this has been done with an anon email you're going to have to redo the commits.

2021-08-02 21:37 UTC, HAFRMO approved these changes

2021-08-03 00:58 UTC, lnewson approved these changes

2021-08-03 01:08 UTC, EkimChau approved these changes

2021-08-03 01:09 UTC, merged