TINY-4603: Renamed variables.
tinymce/tinymce-docs pull request #2185
Opened 2021-12-01 14:31 UTC by HAFRMO

Related Ticket: 

Description of Changes:
Variable names have changed. Not a new product feature.

Pre-checks:
- [x] Branch prefixed with `feature/` or `hotfix/`
- [x] `_data/nav.yml` has been updated (if applicable)
- [x] Files has been included where required (if applicable)
- [x] Files removed have been deleted, not just excluded from the build (if applicable)
- [x] (New product features only) Release Note added

Review:
- [ ] Documentation Team Lead has reviewed
- [ ] Product Manager has reviewed

2021-12-01 17:42 UTC, vpyshnenko approved these changes

2021-12-01 19:33 UTC, lnewson requested changes
This is targeting the wrong branch (it should be targeting the 6.0 feature branch and it also needs some migration/release notes as well.

2021-12-01 19:33 UTC, lnewson commented on _data/nav.yml
> +      - url: "#link_default_target"
These need reordering as previously it was in alphabetical order.

- [ ] Reorder the sections so they remain in alphabetical order please

2021-12-02 13:42 UTC, HAFRMO commented
The addition to the migration-page was left purposefully simple, as was requested in the ticket.

2021-12-02 23:59 UTC, tylerkelly13 commented
@HAFRMO looking good so far, still needs release notes.

2021-12-05 22:17 UTC, lnewson requested changes
As Tyler mentioned part of the work needed is still missing.

2021-12-07 02:15 UTC, tylerkelly13 commented
Also, this branch has a build failure:
```
Could not locate the included file 'configuration/link_default_target.md' in any of ["/pipeline/source/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in plugins-ref/opensource/autolink.md
```

2021-12-09 00:43 UTC, lnewson approved these changes

2021-12-09 00:43 UTC, lnewson commented on release-information/release-notes/6_0_0/6_0_0-release-notes-core-changes.md
> +- The `target_list` option has been renamed to `link_target_list` for the `link` plugin
```suggestion
- The `default_link_target` option has been renamed to `link_default_target` for both `link` and `autolink` plugins.
- The `rel_list` option has been renamed to `link_rel_list` for the `link` plugin.
- The `target_list` option has been renamed to `link_target_list` for the `link` plugin.
```

2021-12-09 00:43 UTC, lnewson commented on how-to-guides/migration-from-5x.md
> +* The `target_list` option has been renamed to `link_target_list` for the `link` plugin
```suggestion
* The `default_link_target` option has been renamed to `link_default_target` for both `link` and `autolink` plugins.
* The `rel_list` option has been renamed to `link_rel_list` for the `link` plugin.
* The `target_list` option has been renamed to `link_target_list` for the `link` plugin.
```

2021-12-09 00:52 UTC, tylerkelly13 approved these changes

2021-12-10 00:52 UTC, EkimChau approved these changes

2021-12-10 01:04 UTC, merged