WSRF- 609 - Add demo support
tinymce/tinymce-docs pull request #2228
Opened 2022-02-15 02:15 UTC by tinyamit

Related Ticket: 
https://ephocks.atlassian.net/browse/WSRF-609

Description of Changes:
* Updated the Antora Docs to support the Demos

Pre-checks:
- [x] Branch prefixed with `feature/` or `hotfix/`
- [n/a] `_data/nav.yml` has been updated (if applicable)
- [x] Files has been included where required (if applicable)
- [x] Files removed have been deleted, not just excluded from the build (if applicable)
- [x] (New product features only) Release Note added

Review:
- [ ] Documentation Team Lead has reviewed
- [ ] Product Manager has reviewed

2022-02-15 02:19 UTC, lnewson requested changes
I'm sorry, but this new format is way to verbose/hard to use as maintainers for the docs. We need something simple like what was there previously.

2022-02-15 02:19 UTC, lnewson commented on modules/ROOT/pages/demo/local-upload.adoc
> +====
This is pretty horrific to try and remember the exact format needed for this... it should be done via a macro like it was previously, as examples should be easy to add.

2022-02-15 02:23 UTC, lnewson commented
Another issue I see with this, is it removes the ability to use variables within the demos which means everything needs to be duplicated and makes this harder to maintain. So it's not the path we should be taking here, as this system is supposed to make things better/easier to maintain.

2022-02-15 02:28 UTC, tinyamit commented on modules/ROOT/pages/demo/local-upload.adoc
> +====
Antora /ASCII doc does not give many options to run JS , the only way I got it is to use pass through block. Otherwise other way around will be dumping all these file to the UI and perform some macro in. But certainly that defies the purpose of have version controlled branches. 
This solution was originally presented by the creator of Antora and is also used by couch base too. There might be a way around this but it may require deeper digging and understanding working of Antora. 

Being said, I am all ears. If you have some better solution I will be happy to listen.

2022-02-15 02:30 UTC, tinyamit commented
> 

I understand that, I have a way around that. But there will still be limitations in regards to what props can be passed. Its usually strings and boolean which can be used as attributes for doc

2022-02-15 02:33 UTC, lnewson commented on modules/ROOT/pages/demo/local-upload.adoc
> +====
As I said and as proved by the previous version, this massive block can be generated by macros. It also allows embedding the JS or creating scripts like this automatically so that writers don't need to manually do it all the time.

2022-02-15 02:36 UTC, tinyamit commented on modules/ROOT/pages/demo/local-upload.adoc
> +====
actually yes, I will change that soon.

2022-02-15 02:36 UTC, lnewson commented on modules/ROOT/pages/demo/local-upload.adoc
> +====
On that note, what was the issue with the thing that Tyler and I had whipped up as a PoC? The Jira mentions nothing and I can't see why it needs to be replaced.

2022-02-15 03:21 UTC, tinyamit commented
@lnewson have a look now ?

2022-02-15 04:06 UTC, lnewson commented
> @lnewson have a look now ?

That's better, but sorry @tinyamit it's still not going to work. The demos need to be dynamic so it needs to be something similar to what was there originally. As as example, sometimes it needs to load from `example.js` for the content to show instead of `index.js` and other times it shouldn't include the CodePen link (e.g. if an example.js file is included there should be no codepen link). I also suspect this wouldn't actually work, as nothing appears to be including the relevant TinyMCE or Tiny Drive scripts from cloud (I can't get the demo working to test). So overall this solution does not appear viable and doesn't meet the requirements needed for documentation authoring and demos.

This really should have been discussed with us before this task was undertaken to be honest, given we are the users/stakeholders when it comes to authoring. You still also haven't answered my previous question:
> On that note, what was the issue with the thing that Tyler and I had whipped up as a PoC? The Jira mentions nothing and I can't see why it needs to be replaced. It was definitely a better/more maintainable solution than manually having to write this out

2022-03-04 00:46 UTC, EkimChau approved these changes

2022-03-29 08:40 UTC, lnewson commented
I'm going to close this because this isn't an approach we're taking at the moment. We can come back to this later if needed.

2022-03-29 08:40 UTC, closed without merging