DOC-1542: Bespoke Names Changes
tinymce/tinymce-docs pull request #2259
Opened 2022-03-09 02:10 UTC by thedrjim

Related Ticket: DOC-1542

Description of Changes:
* Changed updated setting names to there 6v conterparts 

Pre-checks: DOC-1542
- [x] Branch prefixed with `feature/` or `hotfix/`
- [x] `_data/nav.yml` has been updated (if applicable)
- [x] Files has been included where required (if applicable)
- [x] Files removed have been deleted, not just excluded from the build (if applicable)
- [x] (New product features only) Release Note added

Review:
- [x] Documentation Team Lead has reviewed
- [x] Product Manager has reviewed

2022-03-09 06:57 UTC, ltrouton reviewed
Just to note, it looks like the branch is missing the `feature` prefix so should have been `feature/DOC-1542`.

Also, there are several files that need to be updated since a few of the file names have changed. E.g. `include::partial$configuration/font_formats.adoc[]` needs to be changed to `include::partial$configuration/font_family_formats.adoc[]` so it is properly included

2022-03-09 06:57 UTC, ltrouton commented on modules/ROOT/partials/configuration/font_size_formats.adoc
>  == `+fontsize_formats+`
```suggestion
[[font_size_formats]]
== `+font_size_formats+`
```
There also looks to be a few others in the files which haven't been converted

2022-03-09 06:57 UTC, ltrouton commented on modules/ROOT/partials/configuration/style_formats.adoc
> +* Add some custom styles to the `+styles+` dropdown toolbar button and the `+formats+` menu item using the xref:user-formatting-options.adoc#style_formats[style_formats] configuration option.
I belive this needs to be changed as well
```suggestion
* Add some custom styles to the `+styles+` dropdown toolbar button and the `+styles+` menu item using the xref:user-formatting-options.adoc#style_formats[style_formats] configuration option.
```

2022-03-09 06:59 UTC, lnewson commented
I'm converting this back to a draft as I know @thedrjim is working on the includes, xrefs, etc... we should convert it back when that's done to save others reviewing this when it's not really ready yet.

2022-03-11 04:33 UTC, EkimChau approved these changes

2022-03-13 23:42 UTC, lnewson commented on modules/ROOT/partials/toolbar-button-ids/core-toolbar-buttons.adoc
> +|`+blocks+` |Dropdown list with block formats to apply to selection.
This probably needs move up before `bold`, as this list is alphabetical.

2022-03-15 02:26 UTC, lnewson commented on modules/ROOT/examples/live-demos/web-component/example.html
> +      toolbar="undo redo | fontfamily | bold italic backcolor |
```suggestion
      toolbar="undo redo | blocks | bold italic backcolor |
```

2022-03-15 02:26 UTC, lnewson commented on modules/ROOT/examples/live-demos/web-component/index.html
> +      toolbar="undo redo | fontfamily | bold italic backcolor |
```suggestion
      toolbar="undo redo | blocks | bold italic backcolor |
```

2022-03-15 02:28 UTC, lnewson commented on modules/ROOT/partials/configuration/style_formats.adoc
> +This option allows you to define custom items for the `+styles+` dropdown toolbar button and the `+formats+` menu item.
```suggestion
This option allows you to define custom items for the `+styles+` dropdown toolbar button and the `+styles+` menu item.
```

2022-03-15 02:28 UTC, lnewson approved these changes

2022-03-16 23:35 UTC, ltrouton approved these changes

2022-03-16 23:35 UTC, ltrouton commented on modules/ROOT/examples/live-demos/checklist/index.js
> +      items: 'checklist | bold italic underline strikethrough superscript subscript codeformat | style blocks fontfamily fontsize align | forecolor backcolor | removeformat'
```suggestion
      items: 'checklist | bold italic underline strikethrough superscript subscript codeformat | styles blocks fontfamily fontsize align | forecolor backcolor | removeformat'
```

2022-03-16 23:35 UTC, ltrouton commented on modules/ROOT/partials/configuration/defaultmenuitems.adoc
> +    format: { title: 'Format', items: 'bold italic underline strikethrough superscript subscript codeformat | style blocks fontfamily fontsize align lineheight | forecolor backcolor | removeformat' }
```suggestion
    format: { title: 'Format', items: 'bold italic underline strikethrough superscript subscript codeformat | styles blocks fontfamily fontsize align lineheight | forecolor backcolor | removeformat' },
```

2022-03-16 23:35 UTC, ltrouton commented on modules/ROOT/partials/integrations/laravel-quick-start.adoc
> +    toolbar: 'undo redo | blocks| bold italic | alignleft aligncenter alignright | indent outdent | bullist numlist | code | table'
```suggestion
    toolbar: 'undo redo | blocks | bold italic | alignleft aligncenter alignright | indent outdent | bullist numlist | code | table'
```

2022-03-17 05:46 UTC, tiny-james approved these changes

2022-03-18 02:08 UTC, metricjs requested changes

2022-03-18 02:08 UTC, metricjs commented on modules/ROOT/partials/menu-item-ids/core-menu-items.adoc
>  |`+formats+` |Format |Menu of all available formats.
This was also renamed to `styles` I believe? Will need to be renamed and moved, to keep alphabetical order. And this description isn't great... We could steal the description from the toolbars list? `Dropdown list with styles to apply to selection.`

2022-03-18 06:29 UTC, metricjs approved these changes

2022-03-18 06:32 UTC, merged