feature/6/DOC-1605: removed image files
tinymce/tinymce-docs pull request #2350
Opened 2022-03-31 06:04 UTC by thedrjim

Related Ticket: DOC:1605

Description of Changes:
* removed unused images

Pre-checks:
- [x] Branch prefixed with `feature/` or `hotfix/`
- [x] `_data/nav.yml` has been updated (if applicable)
- [x] Files has been included where required (if applicable)
- [x] Files removed have been deleted, not just excluded from the build (if applicable)
- [x] (New product features only) Release Note added

Review:
- [ ] Documentation Team Lead has reviewed
- [ ] Product Manager has reviewed

2022-03-31 11:10 UTC, lnewson requested changes
Looks good, all of these aren't used as far as I can tell. Going through the full list however, the following were missed:
- border-width-cell-props.png
- toolbar-group-example.png

2022-04-01 01:58 UTC, lnewson approved these changes

2022-04-03 23:20 UTC, ltrouton approved these changes

2022-04-04 00:46 UTC, metricjs approved these changes

2022-04-04 01:54 UTC, merged