DOC-1907: update Advanced Code Editor documentation to cover new functionality
tinymce/tinymce-docs pull request #2650
Opened 2023-03-20 22:19 UTC by brian-forte

Ticket: DOC-1907: update Advanced Code Editor documentation to cover new functionality.

Changes:
* Copy-edits to cater for documenting future, non-search-related keyboard chords.
* New Advanced Code Editor features now listed in both the intro paragraphs and the live demo.

Pre-checks:
- [x] Branch prefixed with `feature/6/` or `hotfix/6/`
- [x] Changelog entry added
~- [ ] `modules/ROOT/nav.adoc` has been updated (if applicable)~
~- [ ] Files has been included where required (if applicable)~
~- [ ] Files removed have been deleted, not just excluded from the build (if applicable)~
- [ ] (New product features only) Release Note added

Review:
- [ ] Documentation Team Lead has reviewed

2023-03-21 21:32 UTC, kemister85 approved these changes

2023-03-22 00:06 UTC, ltrouton approved these changes

2023-04-03 00:32 UTC, MitchCTiny requested changes

2023-04-03 00:32 UTC, MitchCTiny commented on modules/ROOT/pages/advcode.adoc
> +    "code", "fullscreen", 'advcode',
```suggestion
    "fullscreen", 'advcode',
```
The `code` plugin cannot be used with the `advcode` plugin as they both use the same button.

2023-04-04 05:08 UTC, tiny-ben-tran approved these changes

2023-04-06 02:00 UTC, merged