DOC-1969: lists and advlists plugins, text_patterns, and implicit and explicit list-creation UIs
tinymce/tinymce-docs pull request #2693
Opened 2023-05-04 23:53 UTC by brian-forte

Ticket: lists and advlists plugins, text_patterns, and implicit and explicit list-creation UIs.

Changes:
* Removed references to the `lists` plugin being required for some text-patterns to work: the plugin is not so required.
* edits and additions to multiple files documenting the implicit and explicit list-creation UIs.
* Configuration example edits and additions.

Pre-checks:
- [x] Branch prefixed with `feature/6/` or `hotfix/6/`
- [x] Changelog entry added
- [x] Files has been included where required (if applicable)

Review:
- [ ] Documentation Team Lead has reviewed

2023-05-05 01:57 UTC, kemister85 approved these changes

2023-05-05 01:57 UTC, kemister85 commented on modules/ROOT/partials/configuration/text_patterns.adoc
> +NOTE: Replacement patterns are executed on either pressing the *spacebar* or pressing the *ReTurn* or *Enter* key.
```suggestion
NOTE: Replacement patterns are executed on either pressing the *spacebar* or pressing the *Return* or *Enter* key.
```

2023-05-05 01:57 UTC, kemister85 commented on modules/ROOT/pages/lists.adoc
> +The implicit list-creation UI comes via xref:content-behavior-options.adoc#text_patterns[text patterns]. The default set of `text_patterns` enabled when {productname} is initialised include https://d
```suggestion
The implicit list-creation UI comes via xref:content-behavior-options.adoc#text_patterns[text patterns]. The default set of `text_patterns` enabled when {productname} is initialized include https://daringfireball.net/projects/markdown/syntax[Markdown]-based patterns that {productname} automatically turns into basic ordered and unordered lists.
```

2023-05-05 01:57 UTC, kemister85 commented on modules/ROOT/pages/lists.adoc
> +  `text_patterns` off.
Would be be best to change the below to `false` rather than `off`?
```suggestion
  `text_patterns` false,
```

2023-05-07 23:51 UTC, kemister85 approved these changes

2023-05-10 23:00 UTC, MitchCTiny commented on modules/ROOT/pages/lists.adoc
> +== Basic lists UI: explicit lists UI but no implicit lists UI
Is there any explanation for what is meant by explicit and implicit UI? I'm not sure I understand

2023-05-11 01:07 UTC, TheSpyder requested changes

2023-05-11 01:07 UTC, TheSpyder commented on modules/ROOT/pages/lists.adoc
> +If the xref:advlist.adoc[Advanced Lists] Premium plugin is part of a {productname} configuration, the default `text_patterns` set also includes patterns that provide an implicit UI for generating the
While I'm not opposed to calling it an `implicit ui`, I think we can still make this easier to follow.
```suggestion
It is important to note that, by default, {productname} includes both implicit and explicit list-creation user-interfaces.

Adding the `lists` plugin and the `bullist` and `numlist` toolbar items to a {productname} configuration enables the explicit list-creation user-interface (UI).

The implicit list-creation UI comes via xref:content-behavior-options.adoc#text_patterns[text patterns], which are enabled by default in {productname} version 6. The default set of `text_patterns` enabled when {productname} is initialized include https://daringfireball.net/projects/markdown/syntax[Markdown]-based patterns that {productname} automatically create ordered and unordered lists.
```

Following that, I agree the examples should be simplified and moved to the `text_patterns` documentation. I think we can lose the first two examples and just demonstrate that with the list plugin and list `text_patterns` config but no toolbar buttons, lists can still be inserted.

2025-07-05 00:39 UTC, closed without merging