DOC-1993: Added TINY-9669 to the release notes.
tinymce/tinymce-docs pull request #2733
Opened 2023-05-23 12:41 UTC by kemister85

Ticket: DOC-1993

Changes:
* Added TINY-9669 to the release notes.

Pre-checks:
- [x] Branch prefixed with `feature/6/` or `hotfix/6/`
- [x] Changelog entry added
- [x] ~`modules/ROOT/nav.adoc` has been updated (if applicable)~
- [x] ~Files has been included where required (if applicable)~
- [x] ~Files removed have been deleted, not just excluded from the build (if applicable)~
- [x] ~(New product features only) Release Note added~

Review:
- [x] Documentation Team Lead has reviewed

2023-05-25 05:41 UTC, spocke requested changes
Not sure how this ended up in the docs. The TinyState is a internal test module and should not be documented externally.

2023-05-26 00:01 UTC, kemister85 commented
> Not sure how this ended up in the docs. The TinyState is a internal test module and should not be documented externally.

The changelog entry for this ticket was as below.

> ### Added
- Added `TinyState` module that contains transactional functions for editor states.

2023-05-26 00:20 UTC, kemister85 commented on modules/ROOT/pages/6.5-release-notes.adoc
> +In {productname} 6.5, a fix was implemented that ensures that toolbar buttons and menu items are now properly disabled based on the selection. As a result, when `contenteditable= "false"` content is
```suggestion
=== Toolbar and menu items were not being disabled correctly when selecting noneditable elements inside a `contenteditable= "false"` root.
//#TINY-9669

In previous versions of {productname}, an issue was identified where toolbar and menu items were not being disabled correctly when selecting `contenteditable= "false"` contents inside a `contenteditable= "false"` root.

As a consequence, toolbar buttons and menu items would appear to be enabled even though the buttons and menu items were in a disabled state based on the users current selection.

A fix was applied in {productname} 6.5, that now disables the toolbar buttons and menu items based on the users selection. In addition, if `contenteditable= "true"` contents are selected, the toolbars and menu items are re-enabled.
```

2023-05-26 00:20 UTC, kemister85 commented on modules/ROOT/pages/6.5-release-notes.adoc
> +In {productname} 6.5, a fix was implemented that ensures that toolbar buttons and menu items are now properly disabled based on the selection. As a result, when `contenteditable= "false"` content is
@spocke Please see above re-write suggestion.

2023-06-09 07:03 UTC, spocke approved these changes

2023-06-19 09:30 UTC, brian-forte commented on modules/ROOT/pages/6.5-release-notes.adoc
> +A fix was applied in {productname} 6.5, that now disables the toolbar buttons and menu items based on the users selection. In addition, if `contenteditable= "true"` contents are selected, the toolbar
```suggestion
=== Toolbar and menu items were not disabled correctly when selecting elements with a `contenteditable="false"` attribute inside an editor root with a `contenteditable="false"` attribute set.
//#TINY-9669

In previous versions of {productname}, an issue was identified where toolbar and menu items were not presenting as disabled when the contents of elements with a `contenteditable= "false"` attribute were selected from inside a editor root with a `contenteditable="false"` attribute set.

In this circumstance, toolbar buttons and menu items appeared as enabled even though the buttons and menu items were in a disabled state based on the user’s current selection.

{productname} 6.5 now explicitly disables toolbar buttons and menu items based on the user’s selection.

In addition, if the contents of elements with a `contenteditable="true"` attribute are selected in the same circumstance, the toolbars and menu items are re-enabled.
```

1. Edits and copy-edits.
2. The technically accurate phrases edited into place: _`contenteditable="false"` attribute_ and _`contenteditable="true"` attribute_

2023-06-19 09:35 UTC, brian-forte approved these changes

2023-06-19 12:01 UTC, merged