DOC-2059: Added TINY-9793 to the release notes.
tinymce/tinymce-docs pull request #2773
Opened 2023-06-02 03:04 UTC by kemister85

Ticket: DOC-2059

Changes:
* Added TINY-9793 to the release notes.

Pre-checks:
- [x] Branch prefixed with `feature/6/` or `hotfix/6/`
- [x] Changelog entry added
- [x] ~`modules/ROOT/nav.adoc` has been updated (if applicable)~
- [x] ~Files has been included where required (if applicable)~
- [x] ~Files removed have been deleted, not just excluded from the build (if applicable)~
- [x] ~(New product features only) Release Note added~

Review:
- [ ] Documentation Team Lead has reviewed

2023-06-02 03:59 UTC, kemister85 commented on modules/ROOT/pages/6.5-release-notes.adoc
> +In {productname} 6.5, the voice assistant software will now announce instructions  to the user for adjusting the size of the editor, by using directional arrow keys such as `↑` arrow up, `↓` arrow do
```suggestion
When using voice assistant software in previous versions of {productname}, focusing on the editor resize handle would not announce any instruction.

In version 6.5 instructions for adjusting the size of the editor using arrow keys are announced, when the editor resize handle is focused.
```

2023-06-02 03:59 UTC, kemister85 commented on modules/ROOT/pages/6.5-release-notes.adoc
> +In {productname} 6.5, the voice assistant software will now announce instructions  to the user for adjusting the size of the editor, by using directional arrow keys such as `↑` arrow up, `↓` arrow do
@MitchCTiny reverted copy edits to reflect your entry in the TINY-9793 documentation section as requested.

2023-06-02 04:21 UTC, MitchCTiny approved these changes

2023-06-02 04:21 UTC, MitchCTiny commented on modules/ROOT/pages/6.5-release-notes.adoc
> +In version 6.5 instructions for adjusting the size of the editor using arrow keys are announced, when the editor resize handle is focused.
```suggestion
In {productname} 6.5, instructions for adjusting the size of the editor using arrow keys are now announced upon focusing the editor resize handle, while using voice assistant software.
```

2023-06-04 22:45 UTC, MitchCTiny requested changes

2023-06-04 22:45 UTC, MitchCTiny commented on modules/ROOT/pages/6.5-release-notes.adoc
> +In {productname} 6.5, instructions for adjusting the size of the editor using arrow keys are now announced upon focusing the editor resize handle, while using voice assistant software.
```suggestion
In {productname} 6.5, instructions for adjusting the size of the editor using arrow keys are now announced upon focusing the editor resize handle, while using voice assistant software.

NOTE: In {productname} 6.5 Enterprise, this announcement is only available in English. Additional translations will be added in a future release.
```
There should be a known issue about the translations, both here and under "Known issues". Forgot about this until today, sorry.

2023-06-05 03:52 UTC, MitchCTiny commented on modules/ROOT/pages/6.5-release-notes.adoc
> +NOTE: that future releases of {productname} will include additional translations to provide broader support.
```suggestion
=== Untranslated instructions for editor resize handle when using screen readers

In {productname} 6.5, instructions for using the editor resize handle were introduced, however these instructions are only provided in English.

Translations for these instructions will be added in a future enterprise release.
```
Can be trimmed down.

2023-06-13 22:57 UTC, MitchCTiny approved these changes

2023-06-19 07:10 UTC, brian-forte commented on modules/ROOT/pages/6.5-release-notes.adoc
> +NOTE: In {productname} 6.5 Enterprise, this announcement is only available in English. Additional translations will be added in a future release.
```suggestion
=== Screen readers now announce instructions for using arrow keys to resize the editor when the resize handle is focused
//#TINY-9793

When using voice assistant software in previous versions of {productname}, focusing on the editor resize handle would not announce any instruction.

In {productname} 6.5, instructions for using arrow keys to adjust the editor viewport’s size are now announced upon focusing the editor resize handle, while using voice assistant software.

NOTE: In {productname} 6.5.1, this announcement is only available in English. Additional translations will be added in a future release.
```
Copy-edit for parse-ability.

2023-06-19 09:34 UTC, brian-forte approved these changes

2023-06-19 09:55 UTC, merged