DOC-2241: TinyMCE 6.8.3 release notes
tinymce/tinymce-docs pull request #3048
Opened 2024-01-18 05:28 UTC by kemister85

Ticket: DOC-2241

Changes:
* added `6.8.3-release-notes.adoc` to project; updated `changelog.adoc`, `nav.adoc` and `release-notes.adoc` for the TinyMCE 6.8.3 release.

Pre-checks:
- [x] Branch prefixed with `feature/6/` or `hotfix/6/`
- [x] Changelog entry added
- [x] `modules/ROOT/nav.adoc` has been updated (if applicable)
- [x] Files has been included where required (if applicable)
- [x] Files removed have been deleted, not just excluded from the build (if applicable)
- [x] (New product features only) Release Note added

Review:
- [ ] Documentation Team Lead has reviewed

2024-01-24 03:00 UTC, kemister85 commented on modules/ROOT/pages/6.8.3-release-notes.adoc
> +{productname} 6.8.3 was released for {enterpriseversion} and {cloudname} on <weekday>, <month> <DD>^<st|nd|rd|th>^, <YYYY>. These release notes provide an overview of the changes for {productname} 6.
- [ ] Reminder to update date once confirmed.

2024-01-24 09:50 UTC, vpyshnenko approved these changes

2024-01-24 23:57 UTC, FarzadHayat commented on modules/ROOT/nav.adoc
> +**** xref:6.8.2-release-notes.adoc#overview[Overview]
```suggestion
**** xref:6.8.3-release-notes.adoc#overview[Overview]
```

2024-01-25 00:45 UTC, FarzadHayat requested changes
fix link in nav.adoc

2024-01-25 01:55 UTC, FarzadHayat approved these changes
LGTM ✅

2024-01-30 22:52 UTC, EkimChau commented on modules/ROOT/pages/6.8.3-release-notes.adoc
> +NOTE: Service log level was changed from DEBUG to INFO, to reduce logs verbosity and gain more clarity.
Remove line 47 admonition

2024-01-30 22:53 UTC, EkimChau approved these changes

2024-02-08 01:14 UTC, kemister85 commented on changelog.md
> +- DOC-2241: added `6.8.3-release-notes.adoc` to project; updated `changelog.adoc`, `nav.adoc` and `release-notes.adoc` for the TinyMCE 6.8.3 release.
```suggestion
### 2024-02-08

- DOC-2241: added `6.8.3-release-notes.adoc` to project; updated `changelog.adoc`, `nav.adoc` and `release-notes.adoc` for the TinyMCE 6.8.3 release.
```

2024-02-08 01:16 UTC, kemister85 commented on modules/ROOT/pages/6.8.3-release-notes.adoc
> +{productname} 6.8.3 was released for {enterpriseversion} and {cloudname} on <weekday>, <month> <DD>^<st|nd|rd|th>^, <YYYY>. These release notes provide an overview of the changes for {productname} 6.
```suggestion
{productname} 6.8.3 was released for {enterpriseversion} and {cloudname} on Wednesday, February 08^th^, 2024. These release notes provide an overview of the changes for {productname} 6.8.3, including:
```

2024-02-08 07:19 UTC, kemister85 commented on modules/ROOT/pages/6.8.3-release-notes.adoc
> +* `ephox-spelling.war`: 2.118.20
```suggestion
* `ephox-spelling.war`: 2.118.19
```

2024-02-08 23:56 UTC, merged