DOC-2270_TINY-10314 release notes entry: Clicking to the left or right of a non-editable `div` in Firefox would show two cursors.
tinymce/tinymce-docs pull request #3085
Opened 2024-02-15 03:58 UTC by FarzadHayat

Ticket: DOC-2270
Release notes entry for: TINY-10314

Site: [DOC-2270_TINY-10314 site](http://docs-feature-70-doc-2270tiny-10314.staging.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#clicking-to-the-left-or-right-of-a-non-editable-div-in-firefox-would-show-two-cursors)

Changes:
* DOC-2270_TINY-10314 release notes entry: Clicking to the left or right of a non-editable `div` in Firefox would show two cursors.

Pre-checks:
- [x] Branch prefixed with `feature/7/` or `hotfix/7/`
- [x] Added `release note` entry.

Review:
- [ ] Documentation Team Lead has reviewed

2024-02-15 08:02 UTC, lorenzo-pomili requested changes

2024-02-19 00:13 UTC, FarzadHayat commented on modules/ROOT/pages/7.0-release-notes.adoc
> +Previously in Firefox, when the `FakeCaret` was rendered, in some cases the real caret was incorrectly rendered too
```suggestion
Previously in Firefox, when the `FakeCaret` was rendered, in some cases the real caret was incorrectly rendered too.
```

2024-02-19 00:13 UTC, FarzadHayat commented on modules/ROOT/pages/7.0-release-notes.adoc
> +Previously in Firefox, the editor would render the `FakeCaret` that is used by {productname} to insert the real caret in the editor container.
fixed, thanks for the clarification!

2024-02-19 00:47 UTC, kemister85 approved these changes

2024-02-19 23:44 UTC, FarzadHayat commented
@lorenzo-pomili just FYI, still need your review.

2024-02-21 08:01 UTC, lorenzo-pomili approved these changes

2024-02-21 11:53 UTC, merged