DOC-2387: Add live demo to AI Assistant plugin page
tinymce/tinymce-docs pull request #3260
Opened 2024-04-23 05:14 UTC by FarzadHayat

Ticket: DOC-2387

Site: [Staging branch](http://docs-feature-71-doc-2387.staging.tiny.cloud/docs/tinymce/latest/ai#interactive-example)

Changes:
* DOC-2387: Add live demo to AI Assistant plugin page

Pre-checks:
- [x] Branch prefixed with `feature/<version>/`, `hotfix/<version>/`, `staging/<version>/`, or `release/<version>/`
- [-] `modules/ROOT/nav.adoc` has been updated `(if applicable)`
- [x] Files has been included where required `(if applicable)`
- [x] Files removed have been deleted, not just excluded from the build `(if applicable)`
- [-] Files added for `New product features`, and included a `release note` entry.

Review:
- [ ] Documentation Team Lead has reviewed

2024-04-23 06:55 UTC, danoaky-tiny approved these changes

2024-04-23 07:06 UTC, MitchC1999 approved these changes
Nice job, works perfectly!

2024-04-24 02:53 UTC, kemister85 requested changes
Waiting on feedback

2024-04-24 04:00 UTC, tiny-ben-tran approved these changes

2024-04-24 04:37 UTC, MitchC1999 commented on antora.yml
> +    openai_proxy_token: eyJhbGciOiJFUzM4NCJ9.eyJhdWQiOlsiaHR0cHM6Ly9vcGVuYWkuYWktZGVtby1wcm94eS50aW55LmNsb3VkLyJdLCJleHAiOjE3MTk3NTYwMDAsImh0dHBzOi8vb3BlbmFpLmFpLWRlbW8tcHJveHkudGlueS5jbG91ZC9yb2xlIj
This token is publicly available on the website demos. It is not an OpenAI api key.

2024-04-29 05:00 UTC, kemister85 commented on modules/ROOT/examples/live-demos/ai/index.html
Update the html to match the existing `source` from https://www.tiny.cloud/tinymce/features/ai-integration/

2024-04-29 05:24 UTC, MitchC1999 commented on modules/ROOT/examples/live-demos/ai/index.html
Docs has its own content. Is there a reason we need to use the website content?

2024-04-30 00:32 UTC, FarzadHayat commented
IMPORTANT: Check Jira ticket comments for conversation about infosec of exposing openai proxy url and token. DOC-2387

2024-05-02 01:06 UTC, merged